In [58]:
!pip install deep-translator

import pandas as pd
import numpy as np
import re
from textblob import TextBlob
import nltk
from nltk.corpus import stopwords

# Load your data
data = pd.read_csv("C:/Users/Dell/Desktop/DS/DSnot/akp_tahmin/data.csv")
df = pd.DataFrame(data)

# Check the size and display the DataFrame
print("Data size:", df.size)
print(df.head())  # Display the first few rows for confirmation


Data size: 3746
                                                text  result
0  Son yıllarda Türkiye'yi büyüten ve geliştiren ...       1
1  Ekonomide büyük reformlar yapıldı ve bu sayede...       1
2  Yapılan altyapı projeleri, ülke genelinde büyü...       1
3  Sosyal yardımlar ve destek programları, özelli...       1
4  Demokratikleşme adımları atıldı ve vatandaşlar...       1


In [87]:
df

result                                       filteredText
0          1  recent years, leaders grown developed Turkey. ...
1          1  Major reforms made economy result, business wo...
2          1  Infrastructure projects created major changes ...
3          1  Social aid support programs expanded, especial...
4          1  Steps taken towards democratization significan...
...      ...                                                ...
1868       0                          party's policies disaster
1869       0          AKP leaders cannot govern Turkey ignorant
1870       0             party's politicians thinking interests
1871       0  AKP's ideology destroying Turkey's unity solid...
1872       0          party's actions damaging Turkey's economy

[1873 rows x 2 columns]

In [60]:
# Ensure googletrans-temp is installed and in use

from deep_translator import GoogleTranslator
import pandas as pd
import re
import nltk
from nltk.corpus import stopwords

# Download stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
data = pd.read_csv("C:/Users/Dell/Desktop/DS/DSnot/akp_tahmin/data.csv")
df = pd.DataFrame(data)

# Load data

def temizle_metni(text):
    if isinstance(text, str):
        text = text.lower()
        text = re.sub(r'[^\w\s]', '', text)
        text = re.sub(r'\s+', ' ', text).strip()
        return text
    return None

# Apply cleaning
df["temizText"] = df["text"].apply(temizle_metni)

# Translate and filter text
translated_texts = []
for i in df["temizText"]:
    if i:
        try:
            translated_text = GoogleTranslator(source='auto', target='en').translate(i)
            translated_texts.append(translated_text)
        except Exception as e:
            print(f"Error translating text '{i}': {e}")
            translated_texts.append(None)
    else:
        translated_texts.append(None)

# Remove stopwords
filtered_translations = []
for translated_text in translated_texts:
    if translated_text:
        filtered_translation = ' '.join([word for word in translated_text.split() if word.lower() not in stop_words])
        filtered_translations.append(filtered_translation)
    else:
        filtered_translations.append(None)

df["filteredText"] = filtered_translations
df = df.dropna(subset=['filteredText'])

print(df[['text', 'temizText', 'filteredText']])



[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


                                                   text  \
0     Son yıllarda Türkiye'yi büyüten ve geliştiren ...   
1     Ekonomide büyük reformlar yapıldı ve bu sayede...   
2     Yapılan altyapı projeleri, ülke genelinde büyü...   
3     Sosyal yardımlar ve destek programları, özelli...   
4     Demokratikleşme adımları atıldı ve vatandaşlar...   
...                                                 ...   
1868                . Parti'nin politikaları bir yıkım.   
1869  . AKP liderleri Türkiye'yi yönetemez ve bilgisiz.   
1870   Parti'nin politikacıları kendi çıkarlarını dü...   
1871  . AKP'nin ideolojisi Türkiye'nin birlik ve ber...   
1872  . Parti'nin eylemleri Türkiye'nin ekonomisine ...   

                                              temizText  \
0     son yıllarda türkiyeyi büyüten ve geliştiren l...   
1     ekonomide büyük reformlar yapıldı ve bu sayede...   
2     yapılan altyapı projeleri ülke genelinde büyük...   
3     sosyal yardımlar ve destek programları özellik...

In [43]:
df

text  result  \
0  Son yıllarda Türkiye'yi büyüten ve geliştiren ...       1   
1  Ekonomide büyük reformlar yapıldı ve bu sayede...       1   
2  Yapılan altyapı projeleri, ülke genelinde büyü...       1   
3  Sosyal yardımlar ve destek programları, özelli...       1   
4  Demokratikleşme adımları atıldı ve vatandaşlar...       1   

                                           temizText  \
0  son yıllarda türkiyeyi büyüten ve geliştiren l...   
1  ekonomide büyük reformlar yapıldı ve bu sayede...   
2  yapılan altyapı projeleri ülke genelinde büyük...   
3  sosyal yardımlar ve destek programları özellik...   
4  demokratikleşme adımları atıldı ve vatandaşlar...   

                                        filteredText  
0  recent years, leaders grown developed Turkey. ...  
1  Major reforms made economy result, business wo...  
2  Infrastructure projects created major changes ...  
3  Social aid support programs expanded, especial...  
4  Steps taken towards democratization significan...

In [61]:
df = df.drop(columns=["text"])

In [62]:
df

result                                          temizText  \
0          1  son yıllarda türkiyeyi büyüten ve geliştiren l...   
1          1  ekonomide büyük reformlar yapıldı ve bu sayede...   
2          1  yapılan altyapı projeleri ülke genelinde büyük...   
3          1  sosyal yardımlar ve destek programları özellik...   
4          1  demokratikleşme adımları atıldı ve vatandaşlar...   
...      ...                                                ...   
1868       0                    partinin politikaları bir yıkım   
1869       0      akp liderleri türkiyeyi yönetemez ve bilgisiz   
1870       0  partinin politikacıları kendi çıkarlarını düşü...   
1871       0  akpnin ideolojisi türkiyenin birlik ve beraber...   
1872       0  partinin eylemleri türkiyenin ekonomisine zara...   

                                           filteredText  
0     recent years, leaders grown developed Turkey. ...  
1     Major reforms made economy result, business wo...  
2     Infrastructure projects created major changes ...  
3     Social aid support programs expanded, especial...  
4     Steps taken towards democratization significan...  
...                                                 ...  
1868                          party's policies disaster  
1869          AKP leaders cannot govern Turkey ignorant  
1870             party's politicians thinking interests  
1871  AKP's ideology destroying Turkey's unity solid...  
1872          party's actions damaging Turkey's economy  

[1873 rows x 3 columns]

In [63]:
df = df.drop(columns=["temizText"])

In [64]:
df

result                                       filteredText
0          1  recent years, leaders grown developed Turkey. ...
1          1  Major reforms made economy result, business wo...
2          1  Infrastructure projects created major changes ...
3          1  Social aid support programs expanded, especial...
4          1  Steps taken towards democratization significan...
...      ...                                                ...
1868       0                          party's policies disaster
1869       0          AKP leaders cannot govern Turkey ignorant
1870       0             party's politicians thinking interests
1871       0  AKP's ideology destroying Turkey's unity solid...
1872       0          party's actions damaging Turkey's economy

[1873 rows x 2 columns]

In [65]:
from sklearn.feature_extraction.text import CountVectorizer


In [66]:
y=df.iloc[:,0:1]
X=df.iloc[:,1:2]
X

filteredText
0     recent years, leaders grown developed Turkey. ...
1     Major reforms made economy result, business wo...
2     Infrastructure projects created major changes ...
3     Social aid support programs expanded, especial...
4     Steps taken towards democratization significan...
...                                                 ...
1868                          party's policies disaster
1869          AKP leaders cannot govern Turkey ignorant
1870             party's politicians thinking interests
1871  AKP's ideology destroying Turkey's unity solid...
1872          party's actions damaging Turkey's economy

[1873 rows x 1 columns]

In [67]:
print(len(X))
print(len(y))



1873
1873


In [68]:

print(df.isnull().sum()) #

result          0
filteredText    0
dtype: int64


In [69]:
print(len(X))
print(len(y))


1873
1873


In [94]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd



# CountVectorizer'ı başlatma
vectorizer = CountVectorizer()

# Metin verisini sayısallaştırma
X = vectorizer.fit_transform(df['filteredText'])

# Sonuçları görmek için
print("Öznitelik adları (kelimeler):", vectorizer.get_feature_names_out())
print("Sayısallaştırılmış veri:\n", X.toarray())

Öznitelik adları (kelimeler): ['2023' 'ability' 'able' ... 'young' 'younger' 'youth']
Sayısallaştırılmış veri:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [95]:
df["result"].size


1873

In [97]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

# Verilerinizi eğitim ve test olarak ayırın
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Model tanımlamaları
models = {
    "Gaussian Naive Bayes": GaussianNB(),
}

# Modelleri eğitip doğruluklarını karşılaştırın
accuracies = {}

for model_name, model in models.items():
    model.fit(X_train.toarray(), np.ravel(y_train))  # Modeli eğitin
    y_pred = model.predict(X_test.toarray())          # Tahmin yapın
    accuracy = accuracy_score(y_test, y_pred)         # Doğruluğu hesaplayın
    accuracies[model_name] = accuracy                  # Sonuçları saklayın

# Sonuçları yazdırın
for model_name, accuracy in accuracies.items():
    print(f"{model_name} Modelinin Doğruluğu: {accuracy:.2f}")


Gaussian Naive Bayes Modelinin Doğruluğu: 0.86


In [110]:
metin=vectorizer.transform(["chp iyi"])
y_pred=model.predict(metin.toarray())
print(y_pred)



[1]


In [ ]:
import pickle
model="akp.pickle"
pickle.dump(clf,open(model,"wb")) 
with open('vectorizer.pickle', 'wb') as f:
    pickle.dump(vectorizer, f)

çözüm Yolu:

Veri Ön İşleme:

Temizleme: Cümlelerdeki noktalama işaretleri, sayılar ve gereksiz karakterler gibi gürültüyü temizleyin.
Tokenleştirme: Cümleleri kelime veya alt kelime birimlerine (token) ayırın.
Küçük Harfe Çevirme: Tüm kelimeleri küçük harfe çevirerek tutarlılık sağlayın.
Durulama: Sık kullanılan ancak anlamsal olarak çok katkı sağlamayan kelimeleri (stop words) kaldırın.
Köksöz Bulma: Kelimeleri köksözlerine indirgeyerek kelime varyasyonlarını tek bir köksöz altında toplayın (stemming veya lemmatization).
Vektörleştirme:

Bag-of-Words: Kelimelerin metin içindeki sıklıklarını sayarak sayısal bir vektör oluşturun.
TF-IDF: Kelimelerin bir belge içindeki önemini ve tüm belgedeki nadirliğini dikkate alarak ağırlıklandırılmış bir vektör oluşturun.
Word Embeddings: Kelimeleri anlamsal ve sözdizimsel olarak benzer kelimelerle birlikte düşük boyutlu bir uzaya yerleştiren yoğun vektörler kullanın (Word2Vec, GloVe, BERT gibi).


Bu tür bir metin sınıflandırma projesi için aşağıdaki adımları izleyebilirsiniz:

1. Veri Ön İşleme
Öncelikle, verinizi temizlemeniz ve ön işlemeniz gerekiyor. Bu adımlar şunları içerebilir:

Büyük/küçük harf dönüşümü: Metni tek bir formatta (genellikle küçük harf) tutun.
Noktalama işaretleri ve özel karakterler: Gereksiz noktalama işaretlerini ve özel karakterleri kaldırın.
Kelime kökleri: Kelimeleri köklerine indirgemek için lemmatization veya stemming uygulayın.
Stop word'ler: Anlamsız kelimeleri (ve, ve, ama gibi) kaldırın.
2. Özellik Çıkarma
Metinleri sayısal verilere dönüştürmek için çeşitli yöntemler kullanabilirsiniz:

Bag of Words (BoW): Metni kelime frekanslarıyla temsil eder.
TF-IDF (Term Frequency-Inverse Document Frequency): Kelimelerin metin içindeki önemini ölçer.
Word Embeddings: GloVe veya Word2Vec gibi yöntemlerle kelimeleri vektörlere dönüştürerek daha anlamlı temsil sağlar.
3. Model Seçimi
Sınıflandırma algoritmaları arasında seçim yapabilirsiniz. Yaygın olarak kullanılan bazı algoritmalar şunlardır:

Naive Bayes: Metin verileri için basit ve etkili bir yöntem.
Logistic Regression: İkili sınıflandırma için iyi sonuçlar verebilir.
Support Vector Machines (SVM): Yüksek boyutlu veri setlerinde iyi performans gösterir.
Random Forest veya Gradient Boosting: Daha karmaşık modeller, genellikle daha iyi sonuçlar verir.
Derin Öğrenme: RNN veya LSTM gibi modeller, özellikle büyük veri setlerinde etkili olabilir.
4. Modeli Eğitme
Verilerinizi eğitim ve test setlerine ayırın (örneğin, %80 eğitim, %20 test). Seçtiğiniz modelle eğitim setinde eğitin ve ardından test setinde doğruluğunu ölçün.

5. Değerlendirme
Modelinizin performansını değerlendirmek için aşağıdaki metrikleri kullanabilirsiniz:

Doğruluk: Doğru sınıflandırılan örneklerin oranı.
F1 Skoru: Kesinlik ve hatırlamanın birleşimi.
Confusion Matrix: Sınıflandırma hatalarını görselleştirmek için kullanılır.
6. İyileştirme
Modelinizin performansını artırmak için şu yöntemleri düşünebilirsiniz:

Hyperparameter Tuning: Modelin parametrelerini optimize edin.
Özellik Seçimi: Sadece en iyi özellikleri kullanarak modelinizi basitleştirin.
Ensemble Yöntemleri: Farklı modelleri birleştirere