In [1]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv("C:/Users/Dell/Desktop/DS/DSnot/akp_tahmin/data.csv")

In [4]:
data.head()

text  result
0  Son yıllarda Türkiye'yi büyüten ve geliştiren ...       1
1  Ekonomide büyük reformlar yapıldı ve bu sayede...       1
2  Yapılan altyapı projeleri, ülke genelinde büyü...       1
3  Sosyal yardımlar ve destek programları, özelli...       1
4  Demokratikleşme adımları atıldı ve vatandaşlar...       1

In [5]:
df=pd.DataFrame(data)
df.size

3746

In [6]:
df.head()

text  result
0  Son yıllarda Türkiye'yi büyüten ve geliştiren ...       1
1  Ekonomide büyük reformlar yapıldı ve bu sayede...       1
2  Yapılan altyapı projeleri, ülke genelinde büyü...       1
3  Sosyal yardımlar ve destek programları, özelli...       1
4  Demokratikleşme adımları atıldı ve vatandaşlar...       1

In [7]:
df["text"].head

<bound method NDFrame.head of 0       Son yıllarda Türkiye'yi büyüten ve geliştiren ...
1       Ekonomide büyük reformlar yapıldı ve bu sayede...
2       Yapılan altyapı projeleri, ülke genelinde büyü...
3       Sosyal yardımlar ve destek programları, özelli...
4       Demokratikleşme adımları atıldı ve vatandaşlar...
                              ...                        
1868                  . Parti'nin politikaları bir yıkım.
1869    . AKP liderleri Türkiye'yi yönetemez ve bilgisiz.
1870     Parti'nin politikacıları kendi çıkarlarını dü...
1871    . AKP'nin ideolojisi Türkiye'nin birlik ve ber...
1872    . Parti'nin eylemleri Türkiye'nin ekonomisine ...
Name: text, Length: 1873, dtype: object>

In [8]:
import pandas as pd
import re


def temizle_metni(text):
    if isinstance(text, str):
        # Küçük harfe dönüştür
        text = text.lower()
        
        # Noktalama işaretlerini temizle
        text = re.sub(r'[^\w\s]', '', text)
        
        # Boşlukları temizle
        text = re.sub(r'\s+', ' ', text).strip()
        
        return text
df["temizText"] = df["text"].apply(temizle_metni)
df.head()

text  result  \
0  Son yıllarda Türkiye'yi büyüten ve geliştiren ...       1   
1  Ekonomide büyük reformlar yapıldı ve bu sayede...       1   
2  Yapılan altyapı projeleri, ülke genelinde büyü...       1   
3  Sosyal yardımlar ve destek programları, özelli...       1   
4  Demokratikleşme adımları atıldı ve vatandaşlar...       1   

                                           temizText  
0  son yıllarda türkiyeyi büyüten ve geliştiren l...  
1  ekonomide büyük reformlar yapıldı ve bu sayede...  
2  yapılan altyapı projeleri ülke genelinde büyük...  
3  sosyal yardımlar ve destek programları özellik...  
4  demokratikleşme adımları atıldı ve vatandaşlar...

In [9]:
df = df.drop(columns=["text"])

In [10]:
df.head()

result                                          temizText
0       1  son yıllarda türkiyeyi büyüten ve geliştiren l...
1       1  ekonomide büyük reformlar yapıldı ve bu sayede...
2       1  yapılan altyapı projeleri ülke genelinde büyük...
3       1  sosyal yardımlar ve destek programları özellik...
4       1  demokratikleşme adımları atıldı ve vatandaşlar...

In [11]:
from sklearn.feature_extraction.text import CountVectorizer


In [12]:
df

result                                          temizText
0          1  son yıllarda türkiyeyi büyüten ve geliştiren l...
1          1  ekonomide büyük reformlar yapıldı ve bu sayede...
2          1  yapılan altyapı projeleri ülke genelinde büyük...
3          1  sosyal yardımlar ve destek programları özellik...
4          1  demokratikleşme adımları atıldı ve vatandaşlar...
...      ...                                                ...
1868       0                    partinin politikaları bir yıkım
1869       0      akp liderleri türkiyeyi yönetemez ve bilgisiz
1870       0  partinin politikacıları kendi çıkarlarını düşü...
1871       0  akpnin ideolojisi türkiyenin birlik ve beraber...
1872       0  partinin eylemleri türkiyenin ekonomisine zara...

[1873 rows x 2 columns]

In [13]:
y=df.iloc[:,0:1]

In [14]:
X=df.iloc[:,1:2]

In [15]:
X.head()

temizText
0  son yıllarda türkiyeyi büyüten ve geliştiren l...
1  ekonomide büyük reformlar yapıldı ve bu sayede...
2  yapılan altyapı projeleri ülke genelinde büyük...
3  sosyal yardımlar ve destek programları özellik...
4  demokratikleşme adımları atıldı ve vatandaşlar...

In [16]:
y.head()

result
0       1
1       1
2       1
3       1
4       1

In [17]:
print(df.isnull().sum())  # Hangi sütunlarda kaç tane boş değer var


result       0
temizText    0
dtype: int64


In [18]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df['temizText'])

print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [19]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd



# CountVectorizer'ı başlatma
vectorizer = CountVectorizer()

# Metin verisini sayısallaştırma
X = vectorizer.fit_transform(df['temizText'])

# Sonuçları görmek için
print("Öznitelik adları (kelimeler):", vectorizer.get_feature_names_out())
print("Sayısallaştırılmış veri:\n", X.toarray())

Öznitelik adları (kelimeler): ['2023' 'abartarak' 'abd' ... 'şiddetle' 'şikayetçi' 'şüpheler']
Sayısallaştırılmış veri:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [20]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

# Verilerinizi eğitim ve test olarak ayırın
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Model tanımlamaları
models = {
    "Decision Tree": DecisionTreeClassifier(),
}

# Modelleri eğitip doğruluklarını karşılaştırın
accuracies = {}

for model_name, model in models.items():
    model.fit(X_train.toarray(), np.ravel(y_train))  # Modeli eğitin
    y_pred = model.predict(X_test.toarray())          # Tahmin yapın
    accuracy = accuracy_score(y_test, y_pred)         # Doğruluğu hesaplayın
    accuracies[model_name] = accuracy                  # Sonuçları saklayın

# Sonuçları yazdırın
for model_name, accuracy in accuracies.items():
    print(f"{model_name} Modelinin Doğruluğu: {accuracy:.2f}")


Decision Tree Modelinin Doğruluğu: 0.93


In [21]:
metin=vectorizer.transform([" akp ülkenin baş belası "])
y_pred=model.predict(metin.toarray())
print(y_pred)

[0]


In [167]:
import pickle

In [168]:
model="akp.pickle"

In [169]:
pickle.dump(clf,open(model,"wb")) 


In [170]:
with open('vectorizer.pickle', 'wb') as f:
    pickle.dump(vectorizer, f)

In [171]:
X[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [172]:
df.tail()

result                                          temizText
1868       0                    partinin politikaları bir yıkım
1869       0      akp liderleri türkiyeyi yönetemez ve bilgisiz
1870       0  partinin politikacıları kendi çıkarlarını düşü...
1871       0  akpnin ideolojisi türkiyenin birlik ve beraber...
1872       0  partinin eylemleri türkiyenin ekonomisine zara...

In [190]:
! pip install -U textblob


In [191]:
from textblob import TextBlob
!pip install googletrans==4.0.0-rc1


In [195]:
from textblob import TextBlob
from googletrans import Translator
import json
import nltk
from nltk.corpus import stopwords

# NLTK stopwords'i indir
nltk.download('stopwords')

# İngilizce stopwords listesini al
stop_words = set(stopwords.words('english'))

# Çeviri için Translator nesnesi oluştur
translator = Translator()

# Örnek metin
metin = ["Bu harika bir gün!", "Python programlama dili çok güzel."]

# Çevrilmiş metinleri saklamak için bir liste oluştur
translated_texts = []

# Metinleri çevir
for i in metin:
    # TextBlob nesnesi oluştur
    engMetin = TextBlob(i)  
    # Çeviri yap
    translated_blob = translator.translate(str(engMetin), dest='en')  # TextBlob'ı stringe dönüştür
    # Orijinal ve çevrilmiş metni sakla
    translated_texts.append({
        "original": str(engMetin),  # Orijinal metni string olarak al
        "translation": translated_blob.text  # Çeviriyi al
    })

# Çeviriden sonra stopwords'leri kaldır
for entry in translated_texts:
    translated_text = entry['translation']
    # Metni kelimelere ayır ve stopwords'leri filtrele
    filtered_translation = ' '.join([word for word in translated_text.split() if word.lower() not in stop_words])
    entry['filtered_translation'] = filtered_translation

# Sonuçları JSON formatında yazdır
json_output = json.dumps(translated_texts, ensure_ascii=False, indent=4)
print(json_output)


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


[
    {
        "original": "Bu harika bir gün!",
        "translation": "This is a great day!",
        "filtered_translation": "great day!"
    },
    {
        "original": "Python programlama dili çok güzel.",
        "translation": "Python programming language is very beautiful.",
        "filtered_translation": "Python programming language beautiful."
    }
]


In [196]:
df.head()

result                                          temizText
0       1  son yıllarda türkiyeyi büyüten ve geliştiren l...
1       1  ekonomide büyük reformlar yapıldı ve bu sayede...
2       1  yapılan altyapı projeleri ülke genelinde büyük...
3       1  sosyal yardımlar ve destek programları özellik...
4       1  demokratikleşme adımları atıldı ve vatandaşlar...